- version.go
* create a normal release instead of a draft when tagging by @Songmu in https://github.com/Songmu/rcpr/pull/30
**Full Changelog**: https://github.com/Songmu/rcpr/compare/v0.0.3...v0.0.4
> release v0.0.4

- .github/release.yml
- CHANGELOG.md
- version.go
This pull request is for the next release as v0.0.12 created by [rcpr](https://github.com/Songmu/rcpr). Merging it will tag v0.0.12 to the merge commit and create a GitHub release.
You can modify this branch "rcpr-from-v0.0.11" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file
- Edit and commit the version file specified in the .rcpr configuration file to describe the next version
- Add labels to this pull request like "rcpr:minor" or "rcpr:major" …
> Release for v0.0.12

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.0.13 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.0.13 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.0.12" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.0.13

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.0.14 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.0.14 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.0.13" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.0.14

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.0.15 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.0.15 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.0.14" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.0.15

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.1.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.1.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.0.15" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.1.0

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.1.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.1.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.1.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.1.1

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.1.3 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.1.3 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.1.2" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.1.3

- .tagpr
- config.go
- tagpr.go
Since our project is not using CHANGELOG.md, creating or modifying them by tagpr is not needed for us. This pull request proposes to add a flag to turn on/off the feature by .tagpr configuration file for people who wants turn it off like us.
> feat: Add flag to turn on or off creating/modifying CHANGELOG.md

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.2.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.2.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.1.3" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.2.0

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.3.0 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.3.0 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.2.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.3.0

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.3.1 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.3.1 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.3.0" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.3.1

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.3.2 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.3.2 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.3.1" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.3.2

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.3.3 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.3.3 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.3.2" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.3.3

- CHANGELOG.md
- action.yml
- version.go
This pull request is for the next release as v0.3.4 created by [tagpr](https://github.com/Songmu/tagpr). Merging it will tag v0.3.4 to the merge commit and create a GitHub release.
You can modify this branch "tagpr-from-v0.3.3" directly before merging if you want to change the next version number or other files for the release.
<details>
- Version file …
> Release for v0.3.4

- tagpr.go
In the current implementation, even if a .tagpr file exists and the version file setting is empty, it still detects and updates the file. It is incorrect behavior.
Sometimes version files are intentionally set to an empty string, and in such cases, it is confusing to users to detect version files on tagpr's own. Also, since version file detection is done heuristically, false positives can occur.
After the initial setting, even if it is an empty string, the version file information should be changed by the developers themselves and should not be touched by tagpr.
This behavior was informed by @griffin-stewie. Thanks.
> don't update versionFile configuration if .tagpr file already exists

- tag.go
- tagpr.go
- util.go
SetOutput with stdout in GitHub Actions are deprecated.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
> SetOutput in GitHub Actions with new way

- .tagpr
- README.md
- config.go
I guess it is tagpr, not pcpr. So I fixed it.
Please review.
> Fix a typo

- README.md
Fix the following errors.
```
[Error: .github#L1](https://github.com/org/repo/commit/commit-sha#annotation_xxxxxxxxxxxx)
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```
> Fix syntax errors on docs.

- .github/workflows/tagpr.yaml
Recently, an official Action for retrieving a GitHub App token was released.
https://github.com/actions/create-github-app-token
I propose using this instead of a third-party action. (Also, it may help to update the [README](https://github.com/Songmu/tagpr#synopsis) for new users).
> Use the official actions/create-github-app-token Action instead of tibdex/github-app-token

- tagpr.go
- tagpr_test.go
Hi @Songmu.
I am currently operating a repository with a mix of "semver with v prefix" and "calver without v prefix".
```console
$ gh release list | cut -f 1
v1.1.2
v1.1.1
2023.05.1
2023.05.0
v1.1.0
v1.0.1
2023.03.1
2023.03.0
v1.0.0
2023.02.0
v0.1.0
```
At this time, tagpr may misidentify calver as semver.
If tagpr could determine the `vPrefix` setting more strictly, it would avoid the misidentification, at least in my environment.
I hope you will consider this change.
> Consider vPrefix when retrieving the latest semver tag.

- README.md
Hi @Songmu 
I added a note to the README that if you are using GitHub Enterprise (Server), you need to use `GH_ENTERPRISE_TOKEN` instead of `GITHUB_TOKEN`.
I try to use `tagpr` on GitHub Enterprise (Server), but occurred the bellow error.
This error occurred by Songmu/gitconfig ([source code](https://github.com/Songmu/gitconfig/blob/c9eca57482f95e68b455581f94c1b822e2d3b057/special.go#L52)). Further investigation revealed that it was caused by cli/go-gh, which is used internally.
https://github.com/cli/go-gh/blob/debe718854c4ef26135c2348fd91db360fe5bae8/pkg/auth/auth.go#L62-L92
Ideally, this should be handled by `GITHUB_TOKEN`, but as a temporary solution, I updated README.
> update: added configuration of Github Enteprise

- tag.go
- tagpr.go
- util.go
Show error messages with response metadata(status, x-ratelimit-*) by Action's error message format.
This is useful for troubleshooting.
See also https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
> Add showGHError()

- config.go
- config_test.go
- github.go
- go.mod
- go.sum
- semver.go
- tagpr.go
fixes #170 
When using `secret.GITHUB_TOKEN` as a token to call GitHub API, “Secondary rate limit” error occurred frequently and the process stopped there.
If a “Secondary rate limit” error occurs, wait for a certain period of time and retry according to the response header.
Use [go-github-ratelimit](https://github.com/gofri/go-github-ratelimit/tree/main) for retry mechanism.
I ran tagpr 10 times with the following repositories and the process was completed successfully without rate limit error.
https://github.com/snaka/tagpr-err-reproduce-with-debug/actions/runs/10957866785
Before the fix, the error occurred frequently (3 times in 12 tries) as follows
https://github.com/snaka/tagpr-err-reproduce/actions/runs/10956692059/job/30423254520
> Retry when "Secondary rate limit" error occurs in GitHub API

- README.md
- action.yml
- config.go
You can specify the `.tagpr` file path from the GitHub Actions workflow file.
```yml
- uses: Songmu/tagpr@v1
with:
config: .github/tagpr
```
> Get the config file path from the environment variable

- versionfile.go
Hi!
tagpr detects .github/workflows/*.yml as a version file.
See https://github.com/fujiwara/lambroll/pull/465/files
However, it is unlikely that workflow files are version files.
This PR adds the `.github` directory into skip directories.
> versionfile.go: omit .github directory from processing

- tagpr.go
This PR replaces a hard-coded main branch name, "main", with the `releaseBranch` variable in a git command in `tagpr.go`.
With the original implementation, when a release branch name different from "main" (e.g., "master" or "develop") is specified in the `.tagpr` config file, we encounter the following error during the execution of the `Songmu/tagpr@v1` action:
```
...
Switched to a new branch 'tagpr-from-v1.24.0'
git [add -f .tagpr]
git [commit --allow-empty -am [tagpr] prepare for the next release]
[tagpr-from-v1.24.0 b505e8d25] [tagpr] prepare for the next release
git [log --no-merges --pretty=format:%h %s main..origin/tagpr-from-v1.24.0]
fatal: ambiguous argument 'main..origin/tagpr-from-v1.24.0': unknown revision or path not in the working tree.  👈
Use '--' to separate paths from …
```
> Use `releaseBranch` variable instead of the hard-coded "main" in `git log` command

- README.md
This README update addresses a 403 error caused by insufficient permissions to create labels via GitHub Actions.
```
POST https://api.github.com/repos/monochromegane/kmeans/issues/1/labels: 403 You do not have permission to create labels on this repository. [{Resource:Repository Field:label Code:unauthorized Message:}]
Error: POST https://api.github.com/repos/monochromegane/kmeans/issues/1/labels: 403 You do not have permission to create labels on this repository. [{Resource:Repository Field:label Code:unauthorized Message:}] status:403, ...
Error: Process completed with exit code 1.
```
I believe that tagpr requires additional permissions to create labels via POST requests to issues.
In my repository, it started working correctly after adding the above permission setting.
If this fix is …
> Fix 403 error by adding 'issues: write' permission to GitHub Actions.

- action.yml
In the current implementation of the action, even when we pin a specific version, the installer is still fetched from the `main` branch `HEAD`.
This behavior introduces a **significant supply chain security risk**, as it allows unreviewed or unintended changes in the main branch to be executed in user workflows.
To address this, I have modified the implementation to reduce this risk and ensure more predictable and secure behavior.
> Reducing supply chain risk at actions

- .tagpr
- action.yml
1.  Use the executed composite action ref
Follow the refs referenced from workflows.
Users may use branch, tag, or hash.
```yml
jobs:
job:
runs-on: Ubuntu-Latest
steps:
- uses: Songmu/tagpr@<ref>
```
2.  Use environment variables for the input
GitHub Actions will replace the context with plain text. If users or contributors enter the malformed text, secrets might be exposed.
```yml
jobs:
job:
runs-on: Ubuntu-Latest
steps:
- uses: Songmu/tagpr@<ref>
with:
version: \" || rm -rf / \"
```
> Improve the composite action security

- README.md
- config.go
- tagpr.go
This pull request introduces a new feature to support a `tagpr.postVersionCommand` configuration option, which allows users to specify a command to be executed after versioning during the release process. The changes encompass updates to the documentation, configuration handling, and implementation of the new command execution logic.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L124-R127): Added a description for the new `tagpr.postVersionCommand` configuration option, explaining its purpose and usage.
* `config.go`: 
- Added support for the `tagpr.postVersionCommand` configuration in both environment variables (`envPostVersionCommand`) and Git config (`configPostVersionCommand`). …
> feat: add-post-version-command
